server:
  port: 8002


# DataSource Config
spring:
  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@192.168.8.8:1521:ORCL
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_demo
    username: root
    password: root

mybatis-plus:
  type-aliases-package: com.leeves.user.entity

# Logger Config
logging:
  level:
    com.leeves.datademo: debug